spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/academy
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 10
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace